### ISSUE TITLE
Adding Fineract-CN boilerplates

### ISSUE THREAD

**Issue by maektwain** [muellners/generators-finscale#1]
##### **Overview of the feature request**

Add the fineract-CN template to support fineract style development and template to provision.

Please look into the `/generator/server`

That is where the magic happens through needle templating engine.

##### **Motivation for or Use Case**

Currently the fineract-CN template requires manual efforts , we would down the line a boilerplate which could be automated with pre-insert plugins and effortless integration and entity generation and service generator rather then focusing on setting development.
##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by xurror** [comment]
Raised https://github.com/muellners/finscale-hipsters-generators/pull/2 for this

**Comment by maektwain** [comment]
Seems like some actions are failing, did you run some test locally , else let me test them

**Comment by xurror** [comment]
Well, the best test I could run was generate an App myself. The PR still
needs some finegraining.

**Comment by maektwain** [comment]
I am still testing, will update you
